name: gym_buddy
description: Logging gym app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  flutter_easyloading: ^3.0.5
  get: ^4.6.5
  path_provider: ^2.0.14
  flutter_native_timezone_updated_gradle: ^2.0.3
  flutter_timezone: ^1.0.4
  table_calendar: ^3.0.9
  intl: ^0.18.1
  shared_preferences: ^2.1.0
  iconsax: ^0.0.8
  firebase_core: ^2.12.0
  firebase_auth: ^4.6.0
  font_awesome_flutter: ^10.4.0
  cloud_firestore: ^4.7.0
  flutter_native_splash: ^2.2.19
  smooth_page_indicator: ^1.1.0
  google_sign_in: ^6.1.3
  horizontal_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

fonts:
  - family: DM Sans
    fonts:
      - asset: assets/fonts/DMSans-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/DMSans-Bold.ttf
        weight: 700
      - asset: assets/fonts/DMSans-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/DMSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/DMSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/DMSans-RegularItalic.ttf
        style: italic
        weight: 400
  - family: iconsax
    fonts:
      - asset: assets/fonts/iconsax.ttf